project:
  type: website
  output-dir: docs

website:
  title: "Torch para R en español"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhonatanz
      - icon: linkedin
        href: https://www.linkedin.com/in/jhonatan-zambrano-moreno-59a0b525/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

